import { db, type Food, type FoodBasis } from '../../db';
import { newId } from '../../lib/id';

/**
 * Startovní sada běžných potravin (§9, E-10: „prázdná appka první den").
 * Hodnoty jsou na 100 g/ml, ORIENTAČNÍ podle běžných tabulek složení – po
 * naimportování se dají kdykoliv upravit. Nejsou převzaté z konkrétní licencované
 * databáze (vlastní odhady z obecně známých hodnot), takže bez licenčního omezení.
 * Import je idempotentní: co už podle názvu existuje, se nepřidá.
 */

interface SeedFood {
  name: string;
  kcal: number;
  protein: number;
  carbs: number;
  fat: number;
  basis?: FoodBasis;
  /** Orientační hmotnost 1 kusu v gramech (§2) – jen u potravin, co se běžně počítají na kusy. */
  piece?: number;
}

const BASIC_FOODS: SeedFood[] = [
  // Přílohy, obiloviny, pečivo
  { name: 'Rýže dlouhozrnná (syrová)', kcal: 350, protein: 7, carbs: 78, fat: 1 },
  { name: 'Rýže basmati (syrová)', kcal: 350, protein: 8, carbs: 78, fat: 1 },
  { name: 'Rýže natural (syrová)', kcal: 360, protein: 7, carbs: 76, fat: 2.5 },
  { name: 'Těstoviny semolinové (syrové)', kcal: 360, protein: 12, carbs: 72, fat: 1.5 },
  { name: 'Těstoviny celozrnné (syrové)', kcal: 340, protein: 13, carbs: 64, fat: 2.5 },
  { name: 'Kuskus (suchý)', kcal: 376, protein: 13, carbs: 77, fat: 1 },
  { name: 'Bulgur (suchý)', kcal: 342, protein: 12, carbs: 76, fat: 1.3 },
  { name: 'Jáhly (suché)', kcal: 378, protein: 11, carbs: 73, fat: 4 },
  { name: 'Pohanka (syrová)', kcal: 343, protein: 13, carbs: 72, fat: 3.4 },
  { name: 'Ovesné vločky', kcal: 370, protein: 13, carbs: 60, fat: 7 },
  { name: 'Kroupy (suché)', kcal: 350, protein: 10, carbs: 73, fat: 1.5 },
  { name: 'Krupice pšeničná', kcal: 355, protein: 12, carbs: 73, fat: 1 },
  { name: 'Brambory', kcal: 77, protein: 2, carbs: 17, fat: 0.1, piece: 100 },
  { name: 'Batáty', kcal: 86, protein: 1.6, carbs: 20, fat: 0.1, piece: 130 },
  { name: 'Mouka pšeničná hladká', kcal: 364, protein: 10, carbs: 76, fat: 1 },
  { name: 'Mouka pšeničná polohrubá', kcal: 364, protein: 10, carbs: 76, fat: 1 },
  { name: 'Mouka celozrnná pšeničná', kcal: 340, protein: 13, carbs: 72, fat: 2 },
  { name: 'Strouhanka', kcal: 380, protein: 12, carbs: 72, fat: 4 },
  { name: 'Chléb kmínový', kcal: 250, protein: 8, carbs: 48, fat: 3 },
  { name: 'Chléb žitný', kcal: 250, protein: 8, carbs: 48, fat: 3 },
  { name: 'Rohlík', kcal: 290, protein: 9, carbs: 56, fat: 3 },
  { name: 'Bageta', kcal: 270, protein: 9, carbs: 53, fat: 2 },
  { name: 'Toastový chléb', kcal: 265, protein: 8, carbs: 49, fat: 4 },
  { name: 'Müsli', kcal: 360, protein: 9, carbs: 64, fat: 8 },
  { name: 'Cornflakes', kcal: 378, protein: 7, carbs: 84, fat: 1 },
  // Luštěniny
  { name: 'Čočka (suchá)', kcal: 340, protein: 24, carbs: 52, fat: 1.5 },
  { name: 'Červená čočka (suchá)', kcal: 345, protein: 24, carbs: 56, fat: 1.5 },
  { name: 'Fazole bílé (suché)', kcal: 330, protein: 21, carbs: 50, fat: 1.5 },
  { name: 'Fazole červené (suché)', kcal: 335, protein: 22, carbs: 50, fat: 1.5 },
  { name: 'Cizrna (suchá)', kcal: 364, protein: 19, carbs: 61, fat: 6 },
  { name: 'Hrách (suchý)', kcal: 340, protein: 23, carbs: 60, fat: 1.5 },
  { name: 'Sója (suchá)', kcal: 400, protein: 36, carbs: 30, fat: 20 },
  // Maso a uzeniny
  { name: 'Kuřecí prsa', kcal: 106, protein: 23, carbs: 0, fat: 1.5 },
  { name: 'Kuřecí stehno bez kůže', kcal: 120, protein: 20, carbs: 0, fat: 4.5 },
  { name: 'Krůtí prsa', kcal: 105, protein: 24, carbs: 0, fat: 1 },
  { name: 'Vepřová kýta', kcal: 180, protein: 21, carbs: 0, fat: 10 },
  { name: 'Vepřová panenka', kcal: 143, protein: 21, carbs: 0, fat: 6 },
  { name: 'Vepřová plec', kcal: 210, protein: 18, carbs: 0, fat: 15 },
  { name: 'Vepřový bůček', kcal: 520, protein: 9, carbs: 0, fat: 53 },
  { name: 'Hovězí zadní', kcal: 190, protein: 21, carbs: 0, fat: 11 },
  { name: 'Hovězí svíčková', kcal: 130, protein: 21, carbs: 0, fat: 5 },
  { name: 'Mleté hovězí', kcal: 250, protein: 18, carbs: 0, fat: 20 },
  { name: 'Mleté vepřové', kcal: 270, protein: 17, carbs: 0, fat: 23 },
  { name: 'Slanina', kcal: 540, protein: 12, carbs: 0, fat: 53 },
  { name: 'Šunka drůbeží', kcal: 110, protein: 16, carbs: 1, fat: 4.5 },
  { name: 'Šunka vepřová', kcal: 105, protein: 18, carbs: 1, fat: 3.5 },
  { name: 'Klobása', kcal: 300, protein: 13, carbs: 2, fat: 27 },
  { name: 'Párek', kcal: 260, protein: 11, carbs: 2, fat: 23 },
  { name: 'Salám Vysočina', kcal: 440, protein: 16, carbs: 1, fat: 41 },
  // Ryby a mořské plody
  { name: 'Losos', kcal: 208, protein: 20, carbs: 0, fat: 13 },
  { name: 'Pstruh', kcal: 120, protein: 20, carbs: 0, fat: 4 },
  { name: 'Treska', kcal: 82, protein: 18, carbs: 0, fat: 0.7 },
  { name: 'Makrela', kcal: 205, protein: 19, carbs: 0, fat: 14 },
  { name: 'Tuňák v konzervě (ve vlastní šťávě)', kcal: 116, protein: 26, carbs: 0, fat: 1 },
  { name: 'Sardinky v oleji', kcal: 220, protein: 25, carbs: 0, fat: 13 },
  { name: 'Krevety', kcal: 99, protein: 24, carbs: 0, fat: 0.3 },
  // Mléčné a vejce
  { name: 'Vejce slepičí', kcal: 155, protein: 13, carbs: 1.1, fat: 11, piece: 55 },
  { name: 'Vaječný bílek', kcal: 52, protein: 11, carbs: 0.7, fat: 0.2, piece: 33 },
  { name: 'Vaječný žloutek', kcal: 322, protein: 16, carbs: 3.6, fat: 27, piece: 17 },
  { name: 'Mléko polotučné', kcal: 47, protein: 3.4, carbs: 4.8, fat: 1.5, basis: 'ml' },
  { name: 'Mléko plnotučné', kcal: 62, protein: 3.3, carbs: 4.7, fat: 3.5, basis: 'ml' },
  { name: 'Smetana ke šlehání 33 %', kcal: 320, protein: 2.5, carbs: 3, fat: 33, basis: 'ml' },
  { name: 'Smetana na vaření 12 %', kcal: 127, protein: 3, carbs: 4, fat: 12, basis: 'ml' },
  { name: 'Zakysaná smetana 15 %', kcal: 160, protein: 3, carbs: 3.5, fat: 15 },
  { name: 'Jogurt bílý', kcal: 61, protein: 3.5, carbs: 4.7, fat: 3.3 },
  { name: 'Jogurt řecký', kcal: 133, protein: 9, carbs: 4, fat: 9 },
  { name: 'Tvaroh měkký polotučný', kcal: 130, protein: 18, carbs: 3.5, fat: 4.5 },
  { name: 'Cottage sýr', kcal: 98, protein: 12, carbs: 3, fat: 4 },
  { name: 'Eidam 30 %', kcal: 274, protein: 26, carbs: 0, fat: 17 },
  { name: 'Gouda', kcal: 356, protein: 25, carbs: 0, fat: 28 },
  { name: 'Mozzarella', kcal: 253, protein: 18, carbs: 1, fat: 19 },
  { name: 'Parmezán', kcal: 392, protein: 36, carbs: 3, fat: 25 },
  { name: 'Niva', kcal: 350, protein: 20, carbs: 2, fat: 29 },
  { name: 'Máslo', kcal: 740, protein: 0.8, carbs: 0.6, fat: 82 },
  { name: 'Sádlo', kcal: 900, protein: 0, carbs: 0, fat: 100 },
  { name: 'Margarín', kcal: 720, protein: 0, carbs: 1, fat: 80 },
  // Tuky, oleje, sladidla
  { name: 'Olej řepkový', kcal: 884, protein: 0, carbs: 0, fat: 100, basis: 'ml' },
  { name: 'Olej slunečnicový', kcal: 884, protein: 0, carbs: 0, fat: 100, basis: 'ml' },
  { name: 'Olej olivový', kcal: 884, protein: 0, carbs: 0, fat: 100, basis: 'ml' },
  { name: 'Cukr krystal', kcal: 400, protein: 0, carbs: 100, fat: 0 },
  { name: 'Cukr moučkový', kcal: 400, protein: 0, carbs: 100, fat: 0 },
  { name: 'Hnědý cukr', kcal: 380, protein: 0, carbs: 98, fat: 0 },
  { name: 'Med', kcal: 304, protein: 0.3, carbs: 82, fat: 0 },
  { name: 'Javorový sirup', kcal: 260, protein: 0, carbs: 67, fat: 0 },
  { name: 'Kakao nesladké', kcal: 350, protein: 20, carbs: 25, fat: 14 },
  // Zelenina
  { name: 'Cibule', kcal: 40, protein: 1.1, carbs: 9, fat: 0.1, piece: 110 },
  { name: 'Červená cibule', kcal: 40, protein: 1.1, carbs: 9, fat: 0.1, piece: 110 },
  { name: 'Česnek', kcal: 149, protein: 6, carbs: 33, fat: 0.5, piece: 5 },
  { name: 'Pórek', kcal: 61, protein: 1.5, carbs: 14, fat: 0.3, piece: 150 },
  { name: 'Mrkev', kcal: 41, protein: 0.9, carbs: 10, fat: 0.2, piece: 80 },
  { name: 'Petržel kořen', kcal: 75, protein: 3, carbs: 17, fat: 0.6 },
  { name: 'Celer bulva', kcal: 42, protein: 1.5, carbs: 9, fat: 0.3 },
  { name: 'Řapíkatý celer', kcal: 16, protein: 0.7, carbs: 3, fat: 0.2 },
  { name: 'Rajče', kcal: 18, protein: 0.9, carbs: 3.9, fat: 0.2, piece: 120 },
  { name: 'Rajčata loupaná (konzerva)', kcal: 30, protein: 1.3, carbs: 6, fat: 0.2 },
  { name: 'Rajčatový protlak', kcal: 82, protein: 4, carbs: 19, fat: 0.5 },
  { name: 'Passata (rajčatová)', kcal: 35, protein: 1.5, carbs: 6, fat: 0.3 },
  { name: 'Paprika červená', kcal: 31, protein: 1, carbs: 6, fat: 0.3, piece: 150 },
  { name: 'Paprika zelená', kcal: 20, protein: 0.9, carbs: 4.6, fat: 0.2, piece: 150 },
  { name: 'Cuketa', kcal: 17, protein: 1.2, carbs: 3.1, fat: 0.3, piece: 250 },
  { name: 'Lilek', kcal: 25, protein: 1, carbs: 6, fat: 0.2, piece: 250 },
  { name: 'Okurka', kcal: 15, protein: 0.7, carbs: 3.6, fat: 0.1, piece: 300 },
  { name: 'Brokolice', kcal: 34, protein: 2.8, carbs: 7, fat: 0.4 },
  { name: 'Květák', kcal: 25, protein: 1.9, carbs: 5, fat: 0.3 },
  { name: 'Zelí bílé', kcal: 25, protein: 1.3, carbs: 6, fat: 0.1 },
  { name: 'Kysané zelí', kcal: 19, protein: 0.9, carbs: 4, fat: 0.1 },
  { name: 'Špenát', kcal: 23, protein: 2.9, carbs: 3.6, fat: 0.4 },
  { name: 'Salát hlávkový', kcal: 15, protein: 1.4, carbs: 2.9, fat: 0.2 },
  { name: 'Ředkvička', kcal: 16, protein: 0.7, carbs: 3.4, fat: 0.1 },
  { name: 'Žampiony', kcal: 22, protein: 3, carbs: 3.3, fat: 0.3 },
  { name: 'Kukuřice (konzerva)', kcal: 86, protein: 3, carbs: 19, fat: 1.2 },
  { name: 'Hrášek zelený (mražený)', kcal: 81, protein: 5, carbs: 14, fat: 0.4 },
  { name: 'Fazolové lusky', kcal: 31, protein: 1.8, carbs: 7, fat: 0.1 },
  { name: 'Dýně hokaido', kcal: 40, protein: 1, carbs: 9, fat: 0.1 },
  { name: 'Řepa červená', kcal: 43, protein: 1.6, carbs: 10, fat: 0.2 },
  { name: 'Avokádo', kcal: 160, protein: 2, carbs: 9, fat: 15, piece: 150 },
  // Ovoce
  { name: 'Jablko', kcal: 52, protein: 0.3, carbs: 14, fat: 0.2, piece: 150 },
  { name: 'Hruška', kcal: 57, protein: 0.4, carbs: 15, fat: 0.1, piece: 160 },
  { name: 'Banán', kcal: 89, protein: 1.1, carbs: 23, fat: 0.3, piece: 120 },
  { name: 'Pomeranč', kcal: 47, protein: 0.9, carbs: 12, fat: 0.1, piece: 150 },
  { name: 'Mandarinka', kcal: 53, protein: 0.8, carbs: 13, fat: 0.3, piece: 70 },
  { name: 'Citron', kcal: 29, protein: 1.1, carbs: 9, fat: 0.3, piece: 100 },
  { name: 'Jahody', kcal: 32, protein: 0.7, carbs: 8, fat: 0.3 },
  { name: 'Borůvky', kcal: 57, protein: 0.7, carbs: 14, fat: 0.3 },
  { name: 'Maliny', kcal: 52, protein: 1.2, carbs: 12, fat: 0.7 },
  { name: 'Hroznové víno', kcal: 69, protein: 0.7, carbs: 18, fat: 0.2 },
  { name: 'Broskev', kcal: 39, protein: 0.9, carbs: 10, fat: 0.3, piece: 120 },
  { name: 'Meruňka', kcal: 48, protein: 1.4, carbs: 11, fat: 0.4, piece: 40 },
  { name: 'Švestky', kcal: 46, protein: 0.7, carbs: 11, fat: 0.3, piece: 30 },
  { name: 'Ananas', kcal: 50, protein: 0.5, carbs: 13, fat: 0.1 },
  { name: 'Kiwi', kcal: 61, protein: 1.1, carbs: 15, fat: 0.5, piece: 75 },
  { name: 'Meloun vodní', kcal: 30, protein: 0.6, carbs: 8, fat: 0.2 },
  { name: 'Rozinky', kcal: 299, protein: 3, carbs: 79, fat: 0.5 },
  { name: 'Datle sušené', kcal: 282, protein: 2.5, carbs: 75, fat: 0.4 },
  // Ořechy a semínka
  { name: 'Vlašské ořechy', kcal: 654, protein: 15, carbs: 14, fat: 65 },
  { name: 'Mandle', kcal: 579, protein: 21, carbs: 22, fat: 50 },
  { name: 'Lískové ořechy', kcal: 628, protein: 15, carbs: 17, fat: 61 },
  { name: 'Kešu', kcal: 553, protein: 18, carbs: 30, fat: 44 },
  { name: 'Arašídy', kcal: 567, protein: 26, carbs: 16, fat: 49 },
  { name: 'Slunečnicová semínka', kcal: 584, protein: 21, carbs: 20, fat: 51 },
  { name: 'Dýňová semínka', kcal: 559, protein: 30, carbs: 11, fat: 49 },
  { name: 'Chia semínka', kcal: 486, protein: 17, carbs: 42, fat: 31 },
  { name: 'Lněná semínka', kcal: 534, protein: 18, carbs: 29, fat: 42 },
  { name: 'Sezam', kcal: 573, protein: 18, carbs: 23, fat: 50 },
  { name: 'Kokos strouhaný', kcal: 660, protein: 7, carbs: 24, fat: 64 },
  // Tekutiny, základy, koření
  { name: 'Kokosové mléko', kcal: 200, protein: 2, carbs: 3, fat: 21, basis: 'ml' },
  { name: 'Sójová omáčka', kcal: 60, protein: 8, carbs: 6, fat: 0, basis: 'ml' },
  { name: 'Ocet', kcal: 20, protein: 0, carbs: 0.6, fat: 0, basis: 'ml' },
  { name: 'Kečup', kcal: 100, protein: 1.2, carbs: 24, fat: 0.2 },
  { name: 'Hořčice', kcal: 66, protein: 4, carbs: 5, fat: 4 },
  { name: 'Majonéza', kcal: 680, protein: 1, carbs: 2, fat: 75 },
  { name: 'Droždí čerstvé', kcal: 105, protein: 12, carbs: 12, fat: 2 },
  { name: 'Sůl', kcal: 0, protein: 0, carbs: 0, fat: 0 },
  // Sladké
  { name: 'Čokoláda hořká', kcal: 546, protein: 8, carbs: 46, fat: 38 },
  { name: 'Čokoláda mléčná', kcal: 535, protein: 8, carbs: 59, fat: 30 },
  { name: 'Lískooříšková pomazánka', kcal: 539, protein: 6, carbs: 57, fat: 31 },
  { name: 'Marmeláda', kcal: 250, protein: 0.5, carbs: 62, fat: 0 },
  // Mléčné a alternativy (doplnění)
  { name: 'Skyr', kcal: 63, protein: 11, carbs: 4, fat: 0.2 },
  { name: 'Jogurt řecký 0 %', kcal: 59, protein: 10, carbs: 3.6, fat: 0.4 },
  { name: 'Kefír', kcal: 55, protein: 3.3, carbs: 4.5, fat: 3.3, basis: 'ml' },
  { name: 'Mascarpone', kcal: 430, protein: 5, carbs: 4, fat: 44 },
  { name: 'Ricotta', kcal: 174, protein: 11, carbs: 3, fat: 13 },
  { name: 'Žervé', kcal: 250, protein: 6, carbs: 4, fat: 24 },
  { name: 'Hermelín', kcal: 300, protein: 20, carbs: 1, fat: 24 },
  { name: 'Feta', kcal: 264, protein: 14, carbs: 4, fat: 21 },
  { name: 'Čedar', kcal: 402, protein: 25, carbs: 1.3, fat: 33 },
  { name: 'Kondenzované mléko slazené', kcal: 320, protein: 8, carbs: 55, fat: 8 },
  { name: 'Sušené mléko', kcal: 500, protein: 26, carbs: 38, fat: 26 },
  { name: 'Máslo přepuštěné (ghí)', kcal: 900, protein: 0, carbs: 0, fat: 100 },
  { name: 'Sójové mléko', kcal: 45, protein: 3.3, carbs: 2.5, fat: 1.8, basis: 'ml' },
  { name: 'Ovesné mléko', kcal: 46, protein: 1, carbs: 7, fat: 1.5, basis: 'ml' },
  { name: 'Mandlové mléko', kcal: 22, protein: 0.5, carbs: 3, fat: 1.1, basis: 'ml' },
  // Bílkoviny a alternativy (doplnění)
  { name: 'Tofu', kcal: 120, protein: 13, carbs: 2, fat: 7 },
  { name: 'Tempeh', kcal: 190, protein: 20, carbs: 8, fat: 11 },
  { name: 'Seitan', kcal: 120, protein: 25, carbs: 4, fat: 1.5 },
  { name: 'Krůtí mleté', kcal: 150, protein: 20, carbs: 0, fat: 8 },
  { name: 'Kuřecí křídla', kcal: 200, protein: 18, carbs: 0, fat: 14 },
  { name: 'Vepřová žebra', kcal: 280, protein: 17, carbs: 0, fat: 23 },
  { name: 'Losos uzený', kcal: 180, protein: 18, carbs: 0, fat: 12 },
  { name: 'Chorizo', kcal: 455, protein: 24, carbs: 2, fat: 38 },
  { name: 'Kabanos', kcal: 400, protein: 20, carbs: 1, fat: 35 },
  // Přílohy a obiloviny (doplnění)
  { name: 'Quinoa (suchá)', kcal: 368, protein: 14, carbs: 64, fat: 6 },
  { name: 'Rýže jasmínová (syrová)', kcal: 355, protein: 7, carbs: 79, fat: 0.6 },
  { name: 'Polenta (kukuřičná krupice)', kcal: 350, protein: 8, carbs: 73, fat: 2 },
  { name: 'Ovesná kaše (instantní, suchá)', kcal: 370, protein: 13, carbs: 60, fat: 7 },
  { name: 'Rýžové chlebíčky', kcal: 380, protein: 8, carbs: 81, fat: 3 },
  { name: 'Knäckebrot', kcal: 350, protein: 10, carbs: 65, fat: 3 },
  { name: 'Tortilla pšeničná', kcal: 300, protein: 8, carbs: 50, fat: 7 },
  { name: 'Bramborové noky', kcal: 150, protein: 4, carbs: 32, fat: 0.5 },
  { name: 'Houskový knedlík', kcal: 180, protein: 6, carbs: 36, fat: 1 },
  { name: 'Mandlová mouka', kcal: 600, protein: 21, carbs: 20, fat: 50 },
  { name: 'Kukuřičný škrob (Maizena)', kcal: 380, protein: 0.3, carbs: 91, fat: 0.1 },
  // Luštěniny (doplnění)
  { name: 'Edamame', kcal: 120, protein: 11, carbs: 9, fat: 5 },
  // Ořechy, semínka, pomazánky (doplnění)
  { name: 'Pistácie', kcal: 562, protein: 20, carbs: 28, fat: 45 },
  { name: 'Para ořechy', kcal: 656, protein: 14, carbs: 12, fat: 66 },
  { name: 'Makadamové ořechy', kcal: 718, protein: 8, carbs: 14, fat: 76 },
  { name: 'Arašídové máslo', kcal: 600, protein: 25, carbs: 20, fat: 50 },
  { name: 'Mandlové máslo', kcal: 630, protein: 21, carbs: 19, fat: 56 },
  { name: 'Tahini', kcal: 595, protein: 17, carbs: 21, fat: 54 },
  // Ovoce (doplnění)
  { name: 'Mango', kcal: 60, protein: 0.8, carbs: 15, fat: 0.4, piece: 200 },
  { name: 'Granátové jablko', kcal: 83, protein: 1.7, carbs: 19, fat: 1.2 },
  { name: 'Fíky čerstvé', kcal: 74, protein: 0.8, carbs: 19, fat: 0.3 },
  { name: 'Fíky sušené', kcal: 250, protein: 3, carbs: 64, fat: 1 },
  { name: 'Grapefruit', kcal: 42, protein: 0.8, carbs: 11, fat: 0.1, piece: 250 },
  { name: 'Nektarinka', kcal: 44, protein: 1, carbs: 11, fat: 0.3, piece: 140 },
  { name: 'Třešně', kcal: 63, protein: 1, carbs: 16, fat: 0.2 },
  { name: 'Rybíz červený', kcal: 56, protein: 1.4, carbs: 14, fat: 0.4 },
  { name: 'Brusinky sušené', kcal: 300, protein: 0.1, carbs: 76, fat: 1.4 },
  { name: 'Papája', kcal: 43, protein: 0.5, carbs: 11, fat: 0.3 },
  // Zelenina (doplnění)
  { name: 'Chřest', kcal: 20, protein: 2.2, carbs: 4, fat: 0.1 },
  { name: 'Rukola', kcal: 25, protein: 2.6, carbs: 3.7, fat: 0.7 },
  { name: 'Kapusta', kcal: 49, protein: 4.3, carbs: 9, fat: 0.9 },
  { name: 'Růžičková kapusta', kcal: 43, protein: 3.4, carbs: 9, fat: 0.3 },
  { name: 'Kedluben', kcal: 27, protein: 1.7, carbs: 6, fat: 0.1, piece: 150 },
  { name: 'Fenykl', kcal: 31, protein: 1.2, carbs: 7, fat: 0.2 },
  { name: 'Hlíva ústřičná', kcal: 33, protein: 3.3, carbs: 4, fat: 0.4 },
  { name: 'Sušená rajčata', kcal: 210, protein: 5, carbs: 44, fat: 3 },
  { name: 'Dýně máslová', kcal: 45, protein: 1, carbs: 12, fat: 0.1 },
  // Tekutiny, základy, koření (doplnění)
  { name: 'Kokosový olej', kcal: 890, protein: 0, carbs: 0, fat: 100, basis: 'ml' },
  { name: 'Sezamový olej', kcal: 884, protein: 0, carbs: 0, fat: 100, basis: 'ml' },
  { name: 'Rybí omáčka', kcal: 50, protein: 8, carbs: 4, fat: 0, basis: 'ml' },
  { name: 'Sriracha', kcal: 100, protein: 2, carbs: 20, fat: 1 },
  { name: 'Worcesterská omáčka', kcal: 80, protein: 0, carbs: 19, fat: 0, basis: 'ml' },
  { name: 'Balzamikový ocet', kcal: 90, protein: 0.5, carbs: 17, fat: 0, basis: 'ml' },
  { name: 'Pesto', kcal: 450, protein: 5, carbs: 6, fat: 45 },
  { name: 'Tatarská omáčka', kcal: 400, protein: 1, carbs: 6, fat: 42 },
  { name: 'BBQ omáčka', kcal: 170, protein: 1, carbs: 40, fat: 0.5 },
  { name: 'Ajvar', kcal: 100, protein: 1.5, carbs: 10, fat: 6 },
  { name: 'Hummus', kcal: 230, protein: 8, carbs: 14, fat: 17 },
  { name: 'Kokosová voda', kcal: 20, protein: 0, carbs: 4, fat: 0, basis: 'ml' },
  // Sladké a pochutiny (doplnění)
  { name: 'Nutella', kcal: 539, protein: 6, carbs: 58, fat: 31 },
  { name: 'Lotus Biscoff pomazánka', kcal: 590, protein: 3.5, carbs: 58, fat: 38 },
  { name: 'Lotus Biscoff sušenky', kcal: 484, protein: 6, carbs: 72, fat: 19 },
  { name: 'Bílá čokoláda', kcal: 540, protein: 6, carbs: 59, fat: 32 },
  { name: 'Snickers', kcal: 480, protein: 8, carbs: 60, fat: 23 },
  { name: 'Kinder Bueno', kcal: 570, protein: 9, carbs: 49, fat: 37 },
  { name: 'Oreo sušenky', kcal: 480, protein: 5, carbs: 70, fat: 20 },
  { name: 'Máslové sušenky', kcal: 460, protein: 7, carbs: 72, fat: 15 },
  { name: 'Piškoty', kcal: 390, protein: 9, carbs: 80, fat: 3 },
  { name: 'Perník', kcal: 350, protein: 5, carbs: 75, fat: 3 },
  { name: 'Zmrzlina vanilková', kcal: 200, protein: 3.5, carbs: 24, fat: 11 },
  { name: 'Gumoví medvídci', kcal: 340, protein: 7, carbs: 77, fat: 0 },
  { name: 'Lentilky', kcal: 480, protein: 5, carbs: 70, fat: 20 },
  { name: 'Bramborové chipsy', kcal: 530, protein: 6, carbs: 50, fat: 34 },
  { name: 'Slané tyčinky', kcal: 380, protein: 10, carbs: 76, fat: 3 },
  { name: 'Popcorn', kcal: 480, protein: 10, carbs: 60, fat: 22 },
  { name: 'Kukuřičné křupky', kcal: 520, protein: 6, carbs: 55, fat: 32 },
  { name: 'Agávový sirup', kcal: 310, protein: 0, carbs: 76, fat: 0 },
  { name: 'Vanilkový cukr', kcal: 400, protein: 0, carbs: 100, fat: 0 },
  { name: 'Želatina', kcal: 335, protein: 84, carbs: 0, fat: 0 },
  { name: 'Čokoládové kapky', kcal: 500, protein: 5, carbs: 65, fat: 25 },
  { name: 'Müsli tyčinka', kcal: 400, protein: 6, carbs: 65, fat: 13 },
  { name: 'Proteinová tyčinka', kcal: 350, protein: 30, carbs: 35, fat: 10 },
  { name: 'Protein prášek (syrovátkový)', kcal: 375, protein: 80, carbs: 8, fat: 6 },
  // Nápoje (doplnění)
  { name: 'Pivo světlé', kcal: 43, protein: 0.5, carbs: 3.5, fat: 0, basis: 'ml' },
  { name: 'Víno bílé', kcal: 82, protein: 0, carbs: 2.6, fat: 0, basis: 'ml' },
  { name: 'Víno červené', kcal: 85, protein: 0, carbs: 2.6, fat: 0, basis: 'ml' },
  { name: 'Pomerančový džus', kcal: 45, protein: 0.7, carbs: 10, fat: 0.2, basis: 'ml' },
  { name: 'Kola', kcal: 42, protein: 0, carbs: 10.6, fat: 0, basis: 'ml' },
];

export function basicFoodCount(): number {
  return BASIC_FOODS.length;
}

/** Přidá základní potraviny, které ještě podle názvu neexistují. Vrací počet přidaných. */
export async function seedBasicFoods(): Promise<number> {
  const existing = await db.foods.filter((food) => !food.deletedAt).toArray();
  const have = new Set(existing.map((food) => food.name.toLowerCase()));
  const now = new Date().toISOString();
  const toAdd: Food[] = BASIC_FOODS.filter((food) => !have.has(food.name.toLowerCase())).map(
    (food) => ({
      id: newId(),
      name: food.name,
      brand: null,
      barcode: null,
      basis: food.basis ?? 'g',
      energyKcal: food.kcal,
      proteinG: food.protein,
      carbsG: food.carbs,
      fatG: food.fat,
      pieceGrams: food.piece ?? null,
      source: 'import',
      isFavorite: false,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    }),
  );
  if (toAdd.length > 0) await db.foods.bulkAdd(toAdd);
  return toAdd.length;
}
